org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.parallel=true

# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

mod_version=1.0.0
maven_group=com.exometric
archives_base_name=exometric

fabric_api_version=0.159.0+26.2
